### ISSUE TITLE
No usa region. And hang after clicking ok

### ISSUE THREAD

**Issue by jistjak** [valentinvanelslande/SMM3DSSE#2]
Tried using this on my 3ds xl so i can unlock the tools to make better levels. I have the us version and there is only a eu version in the region select. After clicking ok, it shows error and then it hangs the system. It doesn't crash to home or show arm9 crash handler screen. it just causes everything to become unresponsive. I can't even open rosalina menu. The only thing i can do is hold power for 10 seconds.

**Comment by valentinvanelslande** [comment]
touch the region and use up/down. use homebrew launcher loader to launch the editor.
