### ISSUE TITLE
Stuck at the "Select the region of the game" page

### ISSUE THREAD

**Issue by Lopass-Tenclea** [valentinvanelslande/SMM3DSSE#5]
When I boot the .3ds file, it successfully launches but then nothing happens... 
Maybe because I use a CIA version of the game?

**Comment by valentinvanelslande** [comment]
this is a issue with the library that this uses (ctrlib)

**Comment by Lopass-Tenclea** [comment]
So what shall I do?

Valentin Vanelslande <notifications@github.com> wrote :

> this is a issue with the library that this uses (ctrlib)
>

**Comment by valentinvanelslande** [comment]
nothing.

**Comment by Lopass-Tenclea** [comment]
Must wait for an update, or just delete the files?

**Comment by valentinvanelslande** [comment]
wait

**Comment by valentinvanelslande** [comment]
i tried with a lot of commits of ctrlib, but the issue was happening with all.
i will delete ctrlib and everything that uses it.
